In [82]:
import os
from os.path import isfile, join
import PIL.Image as pilimg
import numpy as np

output = []

##path = directory path##
class ImgToArr:    
    def __init__(self,path,row,length):
        
        #parameter       
        self.path= path
        self.row = row
        self.length = length
    
    def threshold(self,t,P=False):
        
         
        if P== False:
            
            num = 0
            target = []
            
            while num <self.length:
                
                self.dummy = np.zeros([self.row,self.row])    
                n = num+1
                a = pilimg.open(self.path+str(n)+".jpg")
                array = np.array(a)
                array = array[1:,1:]
            
               
                for i in range(16):
                    for j in range(15):
                        
                        self.dummy[i,0]=1
            
                        if array[i,j]>=128:
                            self.dummy[i,j+1] = 0
            
                        else:
                            self.dummy[i,j+1]=1
                    
                            
                #print(dummy)
                
                output.append(self.dummy)
            
                #print(output)
                target.append([t])
                num = num+1
               
                
            data = np.stack(output,axis=0)
            target = np.stack(target,axis = 0)
        
        return np.savez("HG_dataset_noise_P"+str(t)+".npz",data = data, target = target)
        
p='C:/Users/khl36/Hackathon/imgdata/HG/n=5,m=5 no.'

img = ImgToArr(p,16,100)
result = img.threshold(35)

In [84]:
data = np.load('Dataset_noise_P3.npz')
print(data['data'][2])

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
